# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aless\Desktop\uiFILEs\Caricamento.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton
from PyQt5.QtCore import QBasicTimer
import time

class Ui_Caricamento(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(441, 81)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.caricamento = QtWidgets.QProgressBar(Form)
        self.caricamento.setGeometry(QtCore.QRect(20, 30, 401, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.caricamento.setFont(font)
        self.caricamento.setAutoFillBackground(False)
        self.caricamento.setProperty("value", 0)
        self.caricamento.setTextVisible(False)
        self.caricamento.setInvertedAppearance(False)
        self.caricamento.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.caricamento.setObjectName("caricamento")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 441, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayoutWidget.raise_()
        self.caricamento.raise_()
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Caricamento"))
        self.caricamento.setFormat(_translate("Form", "%p%"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Caricamento()
    ui.setupUi(Form)
    Form.show()

    sys.exit(app.exec_())
