# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aless\Desktop\uiFILEs\PaginaScontrini.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import  mysql.connector
import datetime
from datetime import date


class Ui_PaginaScontrini(object):
    def setupUi(self, PaginaScontrini):
        PaginaScontrini.setObjectName("PaginaScontrini")
        PaginaScontrini.resize(840, 571)
        PaginaScontrini.setStyleSheet("background-image: url(C:/Users/aless/Desktop/uiFILEs/ImmaginiScontrini/SfondoScontrini.png);")
        self.TableScontrini = QtWidgets.QTableWidget(PaginaScontrini)
        self.TableScontrini.setGeometry(QtCore.QRect(160, 240, 521, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableScontrini.sizePolicy().hasHeightForWidth())
        self.TableScontrini.setSizePolicy(sizePolicy)
        self.TableScontrini.setStyleSheet(
"background-color: rgb(122, 122, 122);\n"
"alternate-background-color: rgb(218, 218, 218);\n"
"background: none;\n"
"border: 2px solid white;\n"
"border-bottom-color: #20730b;\n"
"td: 100px;\n"
"\n"
"")//da qui in poi set della pagina scontrini
        self.TableScontrini.setObjectName("TableScontrini")
        self.TableScontrini.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.TableScontrini.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableScontrini.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableScontrini.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableScontrini.setHorizontalHeaderItem(3, item)
        self.TableScontrini.horizontalHeader().setDefaultSectionSize(128)
        self.ButtonAggiungiScontrini = QtWidgets.QPushButton(PaginaScontrini)
        self.ButtonAggiungiScontrini.setGeometry(QtCore.QRect(60, 500, 221, 40))
        self.ButtonAggiungiScontrini.setStyleSheet("background-position: center;\n"
"background-image: url(C:/Users/aless/Desktop/uiFILEs/ImmaginiScontrini/ButtonAggiungiScontrini.png);\n"
"border: 2px solid black;\n"
"border-radius: 10px;\n"
"border-color: #20730b;")
        self.ButtonAggiungiScontrini.setText("")
        self.ButtonAggiungiScontrini.setObjectName("ButtonAggiungiScontrini")
        self.ButtonCercaScontrini = QtWidgets.QPushButton(PaginaScontrini)
        self.ButtonCercaScontrini.setGeometry(QtCore.QRect(500, 160, 220, 40))
        self.ButtonCercaScontrini.setStyleSheet("background-position: center;\n"
"background-image: url(C:/Users/aless/Desktop/uiFILEs/ImmaginiScontrini/ButtonCercaScontrini.png);\n"
"border: 2px solid black;\n"
"border-radius: 10px;\n"
"border-color: #20730b;")
        self.ButtonCercaScontrini.setText("")
        self.ButtonCercaScontrini.setObjectName("ButtonCercaScontrini")
        self.ButtonHome = QtWidgets.QPushButton(PaginaScontrini)
        self.ButtonHome.setGeometry(QtCore.QRect(540, 500, 220, 40))
        self.ButtonHome.setStyleSheet("background-position: center;\n"
"background-image: url(C:/Users/aless/Desktop/uiFILEs/ImmaginiScontrini/ButtonHome.png);\n"
"border: 2px solid black;\n"
"border-radius: 10px;\n"
"border-color: #20730b;")
        self.ButtonHome.setText("")
        self.ButtonHome.setObjectName("ButtonHome")
        self.lineEdit = QtWidgets.QLineEdit(PaginaScontrini)
        self.lineEdit.setGeometry(QtCore.QRect(100, 160, 381, 41))
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background: none;\n"
"border: 2px solid black;\n"
"border-radius: 5px;\n"
"border-color: #20730b;\n"
"text-align: center;")
        self.lineEdit.setObjectName("lineEdit")

        self.TableScontrini.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)   //serve per non modificare i campi di una tabella 

        self.caricaDatiScontrini()
        self.ButtonCercaScontrini.clicked.connect(self.cercaDatiScontrini)

        self.retranslateUi(PaginaScontrini)              //funzione automatica di PyQt
        QtCore.QMetaObject.connectSlotsByName(PaginaScontrini)
//carica i dati nella tabella
    def caricaDatiScontrini(self):
        mydb = mysql.connector.connect(host="localhost",user="alessio",password="alessio",database="prova")
        mycursor = mydb.cursor()

        queryTableScontrini = "SELECT * FROM vendita"
        mycursor.execute(queryTableScontrini)
        risultatoQueryScontrini = mycursor.fetchall()
        rigaTabella = 0
        righeTotali = 0

        for row in risultatoQueryScontrini:
            righeTotali += 1

        self.TableScontrini.setRowCount(righeTotali)

        for row in risultatoQueryScontrini:
            self.TableScontrini.verticalHeader().setVisible(bool(0))
            self.TableScontrini.setItem(rigaTabella, 0, QtWidgets.QTableWidgetItem(str(row[0])))
            self.TableScontrini.setItem(rigaTabella, 1, QtWidgets.QTableWidgetItem(str(row[1])))
            self.TableScontrini.setItem(rigaTabella, 2, QtWidgets.QTableWidgetItem(str(row[2])))
            self.TableScontrini.setItem(rigaTabella, 3, QtWidgets.QTableWidgetItem(str(row[3])))

            rigaTabella += 1
// carica i dati che rispettano delle specifiche settate nella tabella
    def cercaDatiScontrini(self):
        richiesta = self.lineEdit.text()
        mydb = mysql.connector.connect(host="localhost",user="alessio",password="alessio",database="prova")
        mycursor = mydb.cursor()

        queryRicercaScontrini = "SELECT * FROM vendita WHERE vendita.IDVendita = '" + richiesta + "'"

        mycursor.execute(queryRicercaScontrini)
        risultatoRicercaScontrini = mycursor.fetchall()

        rigaTabella = 0
        righeTotali = 0

        for row in risultatoRicercaScontrini:
            righeTotali += 1

        self.TableScontrini.setRowCount(righeTotali)

        for row in risultatoRicercaScontrini:
            self.TableScontrini.verticalHeader().setVisible(bool(0))
            self.TableScontrini.setItem(rigaTabella, 0, QtWidgets.QTableWidgetItem(str(row[0])))
            self.TableScontrini.setItem(rigaTabella, 1, QtWidgets.QTableWidgetItem(str(row[1])))
            self.TableScontrini.setItem(rigaTabella, 2, QtWidgets.QTableWidgetItem(str(row[2])))
            self.TableScontrini.setItem(rigaTabella, 3, QtWidgets.QTableWidgetItem(str(row[3])))

            rigaTabella += 1

    def retranslateUi(self, PaginaScontrini):
        _translate = QtCore.QCoreApplication.translate
        PaginaScontrini.setWindowTitle(_translate("PaginaScontrini", "Form"))
        item = self.TableScontrini.horizontalHeaderItem(0)
        item.setText(_translate("PaginaScontrini", "Numero Scontrino"))
        item = self.TableScontrini.horizontalHeaderItem(1)
        item.setText(_translate("PaginaScontrini", "Data Scontrino"))
        item = self.TableScontrini.horizontalHeaderItem(2)
        item.setText(_translate("PaginaScontrini", "Orario Scontrino"))
        item = self.TableScontrini.horizontalHeaderItem(3)
        item.setText(_translate("PaginaScontrini", "ID Utilizzatore"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PaginaScontrini = QtWidgets.QWidget()
    ui = Ui_PaginaScontrini()
    ui.setupUi(PaginaScontrini)
    PaginaScontrini.show()
    sys.exit(app.exec_())
