# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aless\Desktop\uiFILEs\provaGrafico.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib import pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import datetime
from  datetime import date

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(852, 568)

        self.fakeButton = QtWidgets.QPushButton(Form)
        self.fakeButton.setGeometry(QtCore.QRect(622, 10, 220, 40))
        self.fakeButton.setStyleSheet(
                                      "background-image: url(C:/Users/aless/Desktop/uiFILEs/ImmaginiStatistiche/ButtonHome.png);\n"
                                      "border: 2px solid black;\n"
                                      "border-radius: 10px;\n"
                                      "border-color: #20730b;\n"
                                      "background-repeat: no-repeat;")

        vettore = ['','ciao eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee','anucu','acwef']

        self.fakeButton.clicked.connect(self.visualizzaNotifiche)

        self.lista = QtWidgets.QListWidget(Form)
        self.lista.addItems(vettore)
        self.lista.setGeometry(QtCore.QRect(622, 50, 220, 80))
        self.lista.setStyleSheet(
            "border: 2px solid black;\n"
            "border-radius: 10px;\n"
            "border-color: #20730b;\n"
            "background-repeat: no-repeat;")
        self.lista.setVisible(bool(0))






        QtCore.QMetaObject.connectSlotsByName(Form)



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

    def visualizzaNotifiche(self):
        if self.lista.isVisible():
            self.lista.setVisible(bool(0))
        else:
            self.lista.setVisible(bool(1))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())


