# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aless\Desktop\uiFILEs\LoginFinito.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(513, 464)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 521, 471))
        self.frame.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 143, 0, 255), stop:1 rgba(139, 206, 102, 255))")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frameLogo = QtWidgets.QFrame(self.frame)
        self.frameLogo.setGeometry(QtCore.QRect(70, 30, 391, 101))
        self.frameLogo.setStyleSheet("\n"
                                     "background: no-repeat fixed center;\n"
                                     "background-color: transparent;\n"
                                     "background-image: url(C:/Users/aless/Desktop/uiFILEs/drm_logo-removebg-preview.png);\n"
                                     "border-radius: 50px\n"
                                     "")
        self.frameLogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLogo.setObjectName("frameLogo")
        self.labelEmail = QtWidgets.QLabel(self.frame)
        self.labelEmail.setGeometry(QtCore.QRect(20, 180, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.labelEmail.setFont(font)
        self.labelEmail.setStyleSheet("background: transparent;")
        self.labelEmail.setObjectName("labelEmail")
        self.labelPassword = QtWidgets.QLabel(self.frame)
        self.labelPassword.setGeometry(QtCore.QRect(20, 270, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.labelPassword.setFont(font)
        self.labelPassword.setStyleSheet("background: transparent;")
        self.labelPassword.setObjectName("labelPassword")
        self.lEmail = QtWidgets.QLineEdit(self.frame)
        self.lEmail.setGeometry(QtCore.QRect(20, 210, 471, 31))
        self.lEmail.setStyleSheet("border: 1px solid black;\n"
                                  "  border-radius: 5px;\n"
                                  "background: white\n"
                                  "")
        self.lEmail.setObjectName("lEmail")
        self.lEpassword = QtWidgets.QLineEdit(self.frame)
        self.lEpassword.setGeometry(QtCore.QRect(20, 310, 471, 31))
        self.lEpassword.setStyleSheet("border: 1px solid black;\n"
                                      "  border-radius: 5px;\n"
                                      "background: white")
        self.lEpassword.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lEpassword.setObjectName("lEpassword")
        self.buttonLogin = QtWidgets.QPushButton(self.frame)
        self.buttonLogin.setGeometry(QtCore.QRect(380, 420, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.buttonLogin.setFont(font)
        self.buttonLogin.setStyleSheet("border: 1px solid black;\n"
                                       "border-radius: 5px;\n"
                                       "background: white")
        self.buttonLogin.setDefault(False)
        self.buttonLogin.setObjectName("buttonLogin")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(40, 370, 431, 20))
        self.lineEdit.setStyleSheet("background: transparent;\n"
                                    "color: rgb(255, 0, 0);\n"
                                    "border: none;")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login"))
        self.labelEmail.setText(_translate("Form", "Inserisci Email"))
        self.labelPassword.setText(_translate("Form", "Inserisci Password"))
        self.buttonLogin.setText(_translate("Form", "Login"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
