# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aless\Desktop\uiFILEs\PaginaEsiti.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import mysql.connector
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PaginaEsiti(object):
    def setupUi(self, PaginaEsiti):
        PaginaEsiti.setObjectName("PaginaEsiti")
        PaginaEsiti.resize(840, 571)
        PaginaEsiti.setStyleSheet("background-image: url(ImmaginiProgetto/ImmaginiPrenotazioni/SfondoEsiti.png);")
        self.TableEsiti = QtWidgets.QTableWidget(PaginaEsiti)
        self.TableEsiti.setGeometry(QtCore.QRect(220, 240, 381, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableEsiti.sizePolicy().hasHeightForWidth())
        self.TableEsiti.setSizePolicy(sizePolicy)
        self.TableEsiti.setStyleSheet("selection-background-color: rgb(255, 255, 255);\n"
                                      "background-color: rgb(122, 122, 122);\n"
                                      "alternate-background-color: rgb(218, 218, 218);\n"
                                      "background: none;\n"
                                      "border: 2px solid white;\n"
                                      "border-bottom-color: #20730b;\n"
                                      "td: 100px;\n"
                                      "\n"
                                      "")
        self.TableEsiti.setObjectName("TableEsiti")
        self.TableEsiti.setColumnCount(3)
        self.TableEsiti.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableEsiti.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEsiti.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableEsiti.setHorizontalHeaderItem(2, item)
        self.TableEsiti.horizontalHeader().setDefaultSectionSize(119)
        self.ButtonCercaEsiti = QtWidgets.QPushButton(PaginaEsiti)
        self.ButtonCercaEsiti.setGeometry(QtCore.QRect(500, 160, 220, 40))
        self.ButtonCercaEsiti.setStyleSheet("background-position: center;\n"
                                            "background-image: url(ImmaginiProgetto/ImmaginiPrenotazioni/ButtonCercaEsiti.png);\n"
                                            "border: 2px solid black;\n"
                                            "border-radius: 10px;\n"
                                            "border-color: #20730b;")
        self.ButtonCercaEsiti.setText("")
        self.ButtonCercaEsiti.setObjectName("ButtonCercaEsiti")
        self.ButtonHome = QtWidgets.QPushButton(PaginaEsiti)
        self.ButtonHome.setGeometry(QtCore.QRect(540, 500, 220, 40))
        self.ButtonHome.setStyleSheet("background-position: center;\n"
                                      "background-image: url(ImmaginiProgetto/ImmaginiPrenotazioni/ButtonHome.png);\n"
                                      "border: 2px solid black;\n"
                                      "border-radius: 10px;\n"
                                      "border-color: #20730b;")
        self.ButtonHome.setText("")
        self.ButtonHome.setObjectName("ButtonHome")
        self.lineEditCercaEsiti = QtWidgets.QLineEdit(PaginaEsiti)
        self.lineEditCercaEsiti.setGeometry(QtCore.QRect(100, 160, 381, 41))
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(14)
        self.lineEditCercaEsiti.setFont(font)
        self.lineEditCercaEsiti.setStyleSheet("background: none;\n"
                                              "border: 2px solid black;\n"
                                              "border-radius: 5px;\n"
                                              "border-color: #20730b;\n"
                                              "text-align: center;")
        self.lineEditCercaEsiti.setObjectName("lineEditCercaEsiti")

        self.caricaDatiEsiti()
        self.ButtonCercaEsiti.clicked.connect(self.cercaDatiEsiti)

        self.retranslateUi(PaginaEsiti)
        QtCore.QMetaObject.connectSlotsByName(PaginaEsiti)

    def retranslateUi(self, PaginaEsiti):
        _translate = QtCore.QCoreApplication.translate
        PaginaEsiti.setWindowTitle(_translate("PaginaEsiti", "Form"))
        item = self.TableEsiti.horizontalHeaderItem(0)
        item.setText(_translate("PaginaEsiti", "Codice Prenotazione"))
        item = self.TableEsiti.horizontalHeaderItem(1)
        item.setText(_translate("PaginaEsiti", "Esito"))
        item = self.TableEsiti.horizontalHeaderItem(2)
        item.setText(_translate("PaginaEsiti", "Codice Fiscale"))

    def caricaDatiEsiti(self):
        mydb = mysql.connector.connect(host="localhost", user="alessio", password="alessio", database="prova")
        mycursor = mydb.cursor()

        queryTableEsiti = "SELECT * FROM esiti"
        mycursor.execute(queryTableEsiti)
        risultatoQueryEsiti = mycursor.fetchall()
        rigaTabella = 0
        righeTotali = 0

        for row in risultatoQueryEsiti:
            righeTotali += 1

        self.TableEsiti.setRowCount(righeTotali)

        for row in risultatoQueryEsiti:
            self.TableEsiti.verticalHeader().setVisible(bool(0))
            self.TableEsiti.setItem(rigaTabella, 0, QtWidgets.QTableWidgetItem(str(row[0])))
            self.TableEsiti.setItem(rigaTabella, 1, QtWidgets.QTableWidgetItem(str(row[1])))
            self.TableEsiti.setItem(rigaTabella, 2, QtWidgets.QTableWidgetItem(str(row[2])))

            rigaTabella += 1

    def cercaDatiEsiti(self):
        richiesta = str(self.lineEditCercaEsiti.text())
        mydb = mysql.connector.connect(host="localhost", user="alessio", password="alessio", database="prova")
        mycursor = mydb.cursor()

        queryRicercaScontrini = "SELECT * FROM esiti WHERE esiti.IDPrenotazioni = '" + richiesta + "' OR esiti.CodiceFiscale = '"+str(richiesta)+"'"
        mycursor.execute(queryRicercaScontrini)
        risultatoRicercaScontrini = mycursor.fetchall()

        rigaTabella = 0
        righeTotali = 0

        for row in risultatoRicercaScontrini:
            righeTotali += 1

        self.TableEsiti.setRowCount(righeTotali)

        for row in risultatoRicercaScontrini:
            self.TableEsiti.verticalHeader().setVisible(bool(0))
            self.TableEsiti.setItem(rigaTabella, 0, QtWidgets.QTableWidgetItem(str(row[0])))
            self.TableEsiti.setItem(rigaTabella, 1, QtWidgets.QTableWidgetItem(str(row[1])))
            self.TableEsiti.setItem(rigaTabella, 2, QtWidgets.QTableWidgetItem(str(row[2])))


            rigaTabella += 1


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PaginaEsiti = QtWidgets.QWidget()
    ui = Ui_PaginaEsiti()
    ui.setupUi(PaginaEsiti)
    PaginaEsiti.show()
    sys.exit(app.exec_())
