# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\aless\Desktop\uiFILEs\PaginaAggiungiEsito.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

class Ui_AggiungiEsito(object):
    def setupUi(self, AggiungiPrenotazione):
        AggiungiPrenotazione.setObjectName("AggiungiPrenotazione")
        AggiungiPrenotazione.resize(840, 571)
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(14)
        AggiungiPrenotazione.setFont(font)
        AggiungiPrenotazione.setStyleSheet("\n"
                                           "background-image: url(ImmaginiProgetto/ImmaginiPrenotazioni/SfondoAggiungiEsito.png);")
        self.labelCodicePrenotazione = QtWidgets.QLabel(AggiungiPrenotazione)
        self.labelCodicePrenotazione.setGeometry(QtCore.QRect(60, 160, 220, 40))
        self.labelCodicePrenotazione.setStyleSheet("background-image: url(ImmaginiProgetto/ImmaginiPrenotazioni/LabelCodicePrenotazione.png);\n"
                                                   "background-position: center;\n"
                                                   "border-bottom: 2px solid black;\n"
                                                   "border-radius: 20px;\n"
                                                   "border-color: #20730b;")
        self.labelCodicePrenotazione.setText("")
        self.labelCodicePrenotazione.setObjectName("labelCodicePrenotazione")
        self.lineEditCodicePrenotazione = QtWidgets.QLineEdit(AggiungiPrenotazione)
        self.lineEditCodicePrenotazione.setGeometry(QtCore.QRect(300, 160, 381, 40))
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(14)
        self.lineEditCodicePrenotazione.setFont(font)
        self.lineEditCodicePrenotazione.setStyleSheet("background-position: center;\n"
                                                      "border: 2px solid black;\n"
                                                      "border-radius: 10px;\n"
                                                      "border-color: #20730b;\n"
                                                      "padding-left: 10px;")
        self.lineEditCodicePrenotazione.setObjectName("lineEditCodicePrenotazione")
        self.labelCF = QtWidgets.QLabel(AggiungiPrenotazione)
        self.labelCF.setGeometry(QtCore.QRect(60, 220, 220, 40))
        self.labelCF.setStyleSheet("background-image: url(ImmaginiProgetto/ImmaginiPrenotazioni/LabelCodiceFiscale.png);\n"
                                   "background-position: center;\n"
                                   "border-bottom: 2px solid black;\n"
                                   "border-radius: 20px;\n"
                                   "border-color: #20730b;")
        self.labelCF.setText("")
        self.labelCF.setObjectName("labelCF")
        self.labelEsito = QtWidgets.QLabel(AggiungiPrenotazione)
        self.labelEsito.setGeometry(QtCore.QRect(60, 280, 220, 40))
        self.labelEsito.setStyleSheet("background-image: url(ImmaginiProgetto/ImmaginiPrenotazioni/LabelEsito.png);\n"
                                      "background-position: center;\n"
                                      "border-bottom: 2px solid black;\n"
                                      "border-radius: 20px;\n"
                                      "border-color: #20730b;")
        self.labelEsito.setText("")
        self.labelEsito.setObjectName("labelEsito")
        self.lineEditEsito = QtWidgets.QLineEdit(AggiungiPrenotazione)
        self.lineEditEsito.setGeometry(QtCore.QRect(300, 280, 381, 40))
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(14)
        self.lineEditEsito.setFont(font)
        self.lineEditEsito.setStyleSheet("background-position: center;\n"
                                         "border: 2px solid black;\n"
                                         "border-radius: 10px;\n"
                                         "border-color: #20730b;\n"
                                         "padding-left: 10px;")
        self.lineEditEsito.setObjectName("lineEditEsito")
        self.lineEditCF = QtWidgets.QLineEdit(AggiungiPrenotazione)
        self.lineEditCF.setGeometry(QtCore.QRect(300, 220, 381, 40))
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(14)
        self.lineEditCF.setFont(font)
        self.lineEditCF.setStyleSheet("background-position: center;\n"
                                      "border: 2px solid black;\n"
                                      "border-radius: 10px;\n"
                                      "border-color: #20730b;\n"
                                      "padding-left: 10px;")
        self.lineEditCF.setObjectName("lineEditCF")
        self.ButtonConferma = QtWidgets.QPushButton(AggiungiPrenotazione)
        self.ButtonConferma.setGeometry(QtCore.QRect(540, 500, 220, 40))
        self.ButtonConferma.setStyleSheet("background-image: url(ImmaginiProgetto/ImmaginiPrenotazioni/ButtonCONFERMAEsito.png);\n"
                                          "background-position: center;\n"
                                          "border: 2px solid black;\n"
                                          "border-radius: 10px;\n"
                                          "border-color: #20730b;")
        self.ButtonConferma.setText("")
        self.ButtonConferma.setObjectName("ButtonConferma")
        self.ButtonAnnulla = QtWidgets.QPushButton(AggiungiPrenotazione)
        self.ButtonAnnulla.setGeometry(QtCore.QRect(300, 500, 220, 40))
        self.ButtonAnnulla.setStyleSheet("background-image: url(ImmaginiProgetto/ImmaginiPrenotazioni/ButtonANNULLAEsito.png);\n"
                                         "background-position: center;\n"
                                         "border: 2px solid black;\n"
                                         "border-radius: 10px;\n"
                                         "border-color: #20730b;")
        self.ButtonAnnulla.setText("")
        self.ButtonAnnulla.setObjectName("ButtonAnnulla")

        self.retranslateUi(AggiungiPrenotazione)
        QtCore.QMetaObject.connectSlotsByName(AggiungiPrenotazione)

    def retranslateUi(self, AggiungiPrenotazione):
        _translate = QtCore.QCoreApplication.translate
        AggiungiPrenotazione.setWindowTitle(_translate("AggiungiPrenotazione", "Form"))

    def creaNuovoEsito(self):
        codiceprenotazione = self.lineEditCodicePrenotazione.text()
        codicefiscale = self.lineEditCF.text()
        esito = self.lineEditEsito.text()

        mydb = mysql.connector.connect(host="localhost", user="alessio", password="alessio", database="prova")
        mycursor = mydb.cursor()

        queryAggiungiEsito = "INSERT INTO esiti VALUES ('" + codiceprenotazione + " ','"+esito+"','"+codicefiscale+"')"
        mycursor.execute(queryAggiungiEsito)

        mydb.commit()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AggiungiPrenotazione = QtWidgets.QWidget()
    ui = Ui_AggiungiEsito()
    ui.setupUi(AggiungiPrenotazione)
    AggiungiPrenotazione.show()
    sys.exit(app.exec_())
